///
/// Generated by bookexcel
/// Do't modify this file directly, new partial class file instead
///

using System;
using System.Collections;
using System.Collections.Generic;
using LitJson;
using bookrpg.config;
using UnityEngine;

{% if ($package != ''): %}
namespace {%$package%} 
{
{% endif; %}
    public partial class {%$className%} : {%$parentClassName%} 
    {
        public string key;
        public object value;

        ///parse form {%$fileFormat%} 
        public override bool parseFrom(IConfigParser parser)
        {
            try{
                switch (parser.currentRow) 
                {
                    {%
                        $nameIndex = array_search('itemName', $nameRow);
                        $typeIndex = array_search('itemType', $nameRow);
                        $valueIndex = array_search('itemValue', $nameRow);
                        $i = -1;
                        foreach ($dataRow as $row): 
                        $i++;
                        $name = $row[$nameIndex];
                        $ctype = $this->convertType2($row[$typeIndex]);
                        $type = $ctype[0];
                        $arrDeep = $ctype[1];
                        $get = 'getValue';
                        if ($arrDeep == 1) {
                            $get = 'getList';
                        } elseif($arrDeep > 1) {
                            $get = 'getListGroup';
                        }
                    %}
                    case {%$i%}:
                        this.key = "{%$name%}";
                        if (parser.has(this.key)) {
                            this.value = parser.{%$get%}<{%$type%}>(this.key);
                        } else {
                            this.value = parser.{%$get%}<{%$type%}>("itemValue");
                        }
                        break;
                    {% endforeach; %}
                }

                _key1 = key;
                return true;

            } catch(Exception e)
            {
                Debug.LogWarning(e.Message);
                return false;
            }
        }
    }
{% if ($package != ''): %}
}
{% endif; %}