{%echo '<?php'%} 
/**
 * Generated by bookexcel
 * Do't modify this file directly, modify child class file instead
 */

{% if ($package != ''): %}
namespace {%:$this->convertPackage($package)%};
{% endif; %}

{%$filename = $className.$parentSuffix;%}
class {%:$className.$parentSuffix%} extends \{%$parentClassName%} 
{
    public $key;
    public $value;

    /**
     * parse form {%$fileFormat%} 
     */
    public function parseFrom(\IConfigParser $parser)
    {
        try{
            switch ($parser->key())
            {
                {%
                    $nameIndex = array_search('itemName', $nameRow);
                    $typeIndex = array_search('itemType', $nameRow);
                    $i = -1;
                    foreach ($dataRow as $row): 
                    $i++;
                    $name = $row[$nameIndex];
                    list($type, $arrDeep) = $this->convertType2($row[$typeIndex]);
                    $get = 'getValue';
                    if ($arrDeep == 1) {
                        $get = 'getList';
                    } elseif($arrDeep > 1) {
                        $get = 'getListGroup';
                    }
                %}
                case {%$i%}:
                    $this->key = "{%$name%}";
                    if ($parser->has($this->key)) {
                        $this->value = $parser->{%$get%}($this->key, '{%$type%}');
                    } else {
                        $this->value = $parser->{%$get%}('itemValue', '{%$type%}');
                    }
                    break;
                {% endforeach; %}
            }

            $this->_key1 = $this->key;
            return true;

        } catch(\Exception $e)
        {
            // Debug.LogWarning(e.Message);
            return false;
        }
    }
}