///
/// Generated by bookexcel
/// Do't modify this file directly, modify child class file instead
///

using System;
using System.Collections;
using System.Collections.Generic;
using LitJson;
using bookrpg.config;
using UnityEngine;

{%$filename = $className.$parentSuffix;%}
{% if ($package != ''): %}
namespace {%$package%} 
{
{% endif; %}
    public class {%:$managerClassName.$parentSuffix%} : 
        {% if ($TKey1 && $TKey2): %}
        {%$managerParentClass%}<{%$TKey1%}, {%$TKey2%}, {%$TItem%}>
        {% elseif ($TKey1): %}
        {%$managerParentClass%}<{%$TKey1%}, {%$TItem%}>
        {% else: %}
        {%$managerParentClass%}<{%$TItem%}>
        {% endif; %}
    {
        public {%:$managerClassName.$parentSuffix%}()
        {
            var parser = new {%:ucfirst($fileFormat)%}Parser();
            parser.setArrayDelemiter('{%$arrayDelimiter%}', '{%$innerArrayDelimiter%}');
            this.setParser(parser);
            this.resourceName = "{%$exportFile%}";
        }

        {% 
            foreach ($fields as $field): 
            list($type, $arrDeep) = $this->convertType2($field['type']);
            if ($field['createQuery'] && $arrDeep == 0) :
            $name = $field['name'];
            $uname = ucfirst($name);
        %}
        public {%$className%} getItemBy{%$uname%}({%$type%} value)
        {
            foreach (var item in itemList) 
            {
                if (item.{%$name%} == value) {
                    return item;
                }
            }

            return null;
        }

        public IList<{%$className%}> getItemsBy{%$uname%}({%$type%} value)
        {
            var items = new List<{%$className%}>();
            foreach (var item in itemList) 
            {
                if (item.{%$name%} == value) {
                    items.Add(item);
                }
            }
            return items;
        }

        {% endif; %}
        {% endforeach; %}
    }

    public class {%:$className.$parentSuffix%} : {%$parentClassName%} 
    {
        {% foreach ($fields as $field): %}
        protected const string _{%:Util::camelToConst($field['name'])%} = "{%$field['name']%}";
        {% endforeach; %}

        {% foreach ($fields as $field): %}
        /// {%$field['desc']%} 
        public {%$field['type']%} {%$field['name']%} { get; protected set; }
        {% endforeach; %}

        ///parse form {%$fileFormat%} 
        public override bool parseFrom(IConfigParser parser)
        {
            try{
                {% 
                    $pkey = 0;
                    foreach ($fields as $field): 
                    $name = $field['name'];
                    $uname = Util::camelToConst($name);
                    list($type, $arrDeep) = $this->convertType2($field['type']);
                    $get = 'getValue';
                    if ($arrDeep == 1) {
                        $get = 'getList';
                    } elseif($arrDeep > 1) {
                        $get = 'getListGroup';
                    }
                    $isPkey = $field['isPrimaryKey'];
                    $pkey += $isPkey ? 1 : 0;
                %}
                this.{%$name%} = parser.{%$get%}<{%$type%}>(_{%$uname%});
                {% if ($isPkey && $pkey == 1): %}
                this._key1 = this.{%$name%};
                {% elseif ($isPkey && $pkey == 2): %}
                this._key2 = this.{%$name%};
                {% endif; %}
                {% endforeach; %}

                return true;
            } catch(Exception e)
            {
                Debug.LogWarning(e.Message);
                return false;
            }
        }
    }
{% if ($package != ''): %}
}
{% endif; %}